/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;


import function.DBConnection;
import function.validate;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Computer
 */
public class Searching_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Searching_Customer
     */
    
    public Searching_Customer() {
        initComponents();
        this.setAlwaysOnTop(true);
    }

    /**
     *
     */
    private courier c ;
    private boolean wh1;
    public Searching_Customer(int a , boolean wh,courier b) {
        initComponents();
        c=b;
        wh1=wh;
        
        setdata(a);
        
       
    }
    private String s;
    private void setdata(int CustomerID){
        
        if(wh1){
            s="select Cr_id from (select sends.*, row_number() over (partition by cr_id) as rn from sends)t1 where rn = 1 and C_id = ?";
        }
        else{
            s="select Cr_id from (select sends.*, row_number() over (partition by cr_id) as rn from sends)t1 where rn = 2 and C_id = ?";
        }
        
        try
        (
                java.sql.Connection myconn = DBConnection.getConnection();
                
                PreparedStatement st=  myconn.prepareStatement(s);
                ){
                st.setInt(1, CustomerID);
                 ResultSet rs = st.executeQuery();
               //  if(rs.next()){
                 //System.out.print("\nRun");
                 
            while(rs.next()){
               // System.out.print("\nRun1");
                String courierID = String.valueOf(rs.getInt("Cr_id"));
                try
                (
                PreparedStatement st1=  myconn.prepareStatement("Select * from couriers where Cr_id = ?");
                ){
                st1.setInt(1, Integer.parseInt(courierID));
                 ResultSet rs1 = st1.executeQuery();
            if(rs1.next()){
                // System.out.print("\nRun2");
                String CourierID = String.valueOf(rs1.getInt("Cr_id"));
                String status = rs1.getString("status");
                String weight=String.valueOf(rs1.getInt("weight"));
                String type= rs1.getString("type");
                String amout_paid=String.valueOf(rs1.getInt("amt_paid"));
                String EmployeeID=String.valueOf(rs1.getInt("E_id"));
                String tbdata[] ={CourierID,status,weight,type,amout_paid,EmployeeID};
                DefaultTableModel tbmodel =(DefaultTableModel ) jTable1.getModel();
                 tbmodel.addRow(tbdata);    
            }
                    
            
            
            
        }
         catch(Exception e)
                {
                    
               JOptionPane.showMessageDialog(null,e);
                    
                }
            }
        
        //else{
                    
         //       JOptionPane.showMessageDialog(null,"Courier Not Found" );
                
         //   }
            
        }
        catch(Exception e)
        {  
               JOptionPane.showMessageDialog(null,e);    
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back = new javax.swing.JButton();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(747, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Courier ID", "Status", "Weight", "Type", "Amount Paid", "Employee ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        ok.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(482, 482, 482)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbmodel =(DefaultTableModel ) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        int a =Integer.parseInt(tbmodel.getValueAt(selectedRow, 0).toString());
        validate.setCourierValue(a);
        
        this.setVisible(false);
        c.setdata();
    }//GEN-LAST:event_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searching_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searching_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searching_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searching_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searching_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
